# Extra Credit
# 2. Evaluate an big data algorithm tutorial_K-Nearest Neighbors Algorithm 

The K-nearest neighbors (KNN) algorithm:

The K-nearest neighbors (KNN) algorithm is a type of supervised machine learning algorithms. KNN is extremely easy to implement in its most basic form, and yet performs quite complex classification tasks. Rather, it uses all of the data for training while classifying a new data point or instance.

Theory:

It simply calculates the distance of a new data point to all other training data points. It then selects the K-nearest data points, where K can be any integer. Finally it assigns the data point to the class to which the majority of the K data points belong.

In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  

In [3]:
# Import dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names) 

# Show the first 5 row
dataset.head()


sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
# Split dataset into its attributes and labels
X = dataset.iloc[:, :-1].values  
y = dataset.iloc[:, 4].values 

In [5]:
# Create training and test splits
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)  

In [6]:
# Feature scaling
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  

In [7]:
# Import the KNeighborsClassifier class from the sklearn.neighbors library
from sklearn.neighbors import KNeighborsClassifier  

# Initialized with one parameter, 5 seems to be the most commonly used value for KNN algorithm.
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(X_train, y_train)  

# Make predictions on test data
y_pred = classifier.predict(X_test)  

In [8]:
# Evaluate the algorithm
# For evaluating an algorithm, confusion matrix, precision, recall and f1 score are the most commonly used metrics.
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[11  0  0]
 [ 0  6  0]
 [ 0  2 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.75      1.00      0.86         6
 Iris-virginica       1.00      0.85      0.92        13

    avg / total       0.95      0.93      0.94        30



Discussion of the result:

The results show that our KNN algorithm was able to classify all the 30 records in the test set with 100% accuracy. 

Reference:
https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/